name: Pull request utilities

on:
  - pull_request

jobs:
  labeler:
    name: Assign labels to PR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Add custom labels
        uses: actions/labeler@v5

      - name: Add size labels
        uses: pascalgn/size-label-action@v0.5.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sizes: >
            {
              "0": "xs",
              "20": "s",
              "50": "m",
              "200": "l",
              "800": "xl"
            }
  semantic:
    name: Validate PR title
    runs-on: ubuntu-latest

    steps:
      - name: Check for conventional commit title
        uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
